SIZE_X = 8
SIZE_Y = 8
MIN_SIZE_X = 8
MIN_SIZE_Y = 8
MAX_SIZE_X = 1000
MAX_SIZE_Y = 1000

AVIABLE_GAMEMODES = [
    "Classic",
    "War",
    "Infinity"
]

GRADIENT = ".:!/r(l1Z4H9W8$@"

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"